Code refactoring and first version of feedback implemented
bitfocus/companion-module-analogway-livecore pull request #8
Opened 2022-10-21 20:20 UTC by kellhogs

I've sepperated actions and feedback into their own files, and did some refactoring and updating of the code based on what i saw on some newer modules. i've also added feedback support for changing button styles when an input is in program or preview

2022-10-23 19:28 UTC, dnmeid requested changes
Thanks for giving this old module some love!
See comments in code and please also change package.json

2022-10-23 19:28 UTC, dnmeid commented on analogway_livecore.js
> +					let prearr = line.split(',')
prearr is never reasigned, use const

2022-10-23 19:28 UTC, dnmeid commented on analogway_livecore.js
> +					let input = [Number(prearr[0].replace('TAopr', '')), prearr[1]]
input is the same as prearr, can be omitted. Just do replacement of element prearr[0]

2022-10-23 19:28 UTC, dnmeid commented on analogway_livecore.js
> +						tallyPGM.push(input[0])
Number may be pushed multiple times, e.g. if a tally of command gets not thru. Then the feedback is broken.
Better implementation would be `tallyPGM[input[0]] = input[1]`. Then you have the state of each input in the corresponding index. Reading out would give 0 or 1 or undefined if the tally haven't been set.

2022-10-23 19:28 UTC, dnmeid commented on analogway_livecore.js
> +			if (tallyPGM.includes(feedback.options.source)) {
See suggestion above
```suggestion
			if (tallyPGM[feedback.options.source]) {
```

2022-10-23 19:28 UTC, dnmeid commented on analogway_livecore.js
> +			if (tallyPRV.includes(feedback.options.source)) {
same as with 'input_active'

2022-10-23 19:28 UTC, dnmeid commented on feedback.js
> +				},
add min and max properties

2022-10-23 19:28 UTC, dnmeid commented on feedback.js
> +				},
add min and max properties

2022-10-24 16:13 UTC, kellhogs commented
hey @dnmeid thanks for your sugestions. I will try to implement all of them in the next days.

since im fairly new to the github worklow i have a question. Since ive done some edits scince the upload of the merge request i dont exactly know how to handle the update when i implement your changes. Do i just upload the other edits with the changes or is there a better way to handle this

greetings Fabian

2022-10-24 18:58 UTC, kellhogs commented
Forgot about package.json ..... what exactly do you want me to update there?

2022-10-26 17:11 UTC, dnmeid requested changes
It seems you are in the process of a larger modification. As you are the only one currently working at this code, it is perfectly ok to do the development only on your local computer. You can do as many commits in your local repo as you feel you need to. When you are finished and have tested and cleaned  everything and think it is production ready, then you can push your work to your github repo. However on the master branch of the module itself we want to merge PRs as a single commit. That means you should squash your commits into one. If you are working with a lot of commits (which you obviously do) it is also a good idea to implement new stuff in a different branch, that way the master branch stays clean of all the tiny changes of work in progress. Generally please don't do a PR of work in progress, only for finished stuff. If you want to merge different things which you feel are unrelated you can also issue many PRs in different branches, e.g. one for feedbacks, one for presets but you have to make sure that all can be merged without conflicts. Maybe not the best idea for inexperienced people.

Regarding package.json please do a version bump and credit yourself as a contributor.

Regarding the feedbacks in general, you still are missing an initialization of the feedback values after connection to the device. At the moment the feedbacks only reflect the actual device state after a value change has been received. There is a TODO: in the code where the device state should be pulled to initialize the feedback values.

2022-10-26 17:11 UTC, dnmeid commented on analogway_livecore.js
> +				if (line.match(/TAopr\d+,(0|1)$/)) {
Still not a Regex which will exclusive be triggered by the TAopr command. Try renaming a memory to TAopr1,1 and see what happens.

2022-10-27 07:36 UTC, kellhogs commented
Thanks for your input @dnmeid. Im new to actively working with github, so i dont know the best practises and best ways do do stuff so your help ist very welcome here. 

i have actually started working in another branch scince im also using github to sync my work between my laptop and my pc.

i've origianally only wanted to implement the feedback for the inputs, therefor the early pull request. From now on i will try to only do major commits in the master branch.

as for the device state for the feedback system: I havent found a way in the documentation to pull all the states from the device, so i would probably need to loop over every single input to get the initial values. I wasn't shure if thats the best way to implement that.

2022-10-27 07:52 UTC, kellhogs commented on package.json
> +	"format": "prettier --write .",
Put it in the right place. Documentation was stating that it should be added to the module

2023-07-11 21:36 UTC, dnmeid commented
This is now implemented in the latest version, thank you.

2023-07-11 21:36 UTC, closed without merging